version: '3'

tasks:

  templ:
    sources:
      - ./**/*.templ
    generates:
      - ./**/*_templ.go
    cmd: templ generate
  build:
    method: none
    sources: 
      - ./**/*.go
      - exclude: ./**/*_templ.go
    deps: 
      - templ
    cmds:
      - go mod tidy
      - go build -o bin/aoc cmd/main.go 
  default:
    deps:
      - build
    cmds:
      - ./bin/aoc

